import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { Resend } from "resend";
import jsPDF from "jspdf";
import { redis } from "@/lib/kv";

function getResendClient() {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error("Missing RESEND_API_KEY");
  }

  return new Resend(apiKey);
}

type Block = {
  time: string;
  title: string;
  description: string;
  type: string;
  duration: string;
};

type Day = {
  date: string;
  theme: string;
  blocks: Block[];
};

type Itinerary = {
  destination: string;
  days: Day[];
  tips?: string[];
  paid?: boolean;
  createdAt?: number;
};

function verifySignature(rawBody: string, signature: string, secret: string): boolean {
  if (!signature || !secret) {
    return false;
  }

  const normalizedSignature = signature.replace(/^sha256=/i, "").trim();
  const normalizedSecret = secret.replace(/^(["'])|(["'])$/g, "");

  const hmac = crypto.createHmac("sha256", normalizedSecret);
  const digest = hmac.update(rawBody).digest("hex");
  const digestBuffer = Buffer.from(digest, "utf8");
  const signatureBuffer = Buffer.from(normalizedSignature, "utf8");

  if (digestBuffer.length !== signatureBuffer.length) {
    return false;
  }

  return crypto.timingSafeEqual(digestBuffer, signatureBuffer);
}

function generatePDFBuffer(itinerary: any): Buffer {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const gold = [201, 169, 110];
  const dark = [26, 26, 46];
  const cream = [245, 240, 232];
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  function checkPageBreak(height: number) {
    if (y + height > 270) {
      pdf.addPage();
      y = 20;
    }
  }

  // Background
  pdf.setFillColor(dark[0], dark[1], dark[2]);
  pdf.rect(0, 0, pageWidth, 297, "F");

  // Header
  pdf.setTextColor(gold[0], gold[1], gold[2]);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text("EXPLOREYOURROUTE.COM", pageWidth / 2, y, { align: "center" });
  y += 8;

  pdf.setTextColor(cream[0], cream[1], cream[2]);
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text(itinerary.destination, pageWidth / 2, y + 10, { align: "center" });
  y += 20;

  // Gold line
  pdf.setDrawColor(gold[0], gold[1], gold[2]);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Days
  itinerary.days.forEach((day: any, i: number) => {
    checkPageBreak(20);

    // Day header background
    pdf.setFillColor(gold[0], gold[1], gold[2]);
    pdf.roundedRect(margin, y, contentWidth, 10, 2, 2, "F");
    pdf.setTextColor(dark[0], dark[1], dark[2]);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text(`Day ${i + 1} — ${day.date}`, margin + 4, y + 7);
    pdf.setFont("helvetica", "italic");
    pdf.text(day.theme, pageWidth - margin - 4, y + 7, { align: "right" });
    y += 14;

    // Blocks
    day.blocks.forEach((block: any) => {
      checkPageBreak(24);

      pdf.setFillColor(40, 35, 55);
      pdf.roundedRect(margin, y, contentWidth, 22, 2, 2, "F");

      // Time + type
      pdf.setTextColor(gold[0], gold[1], gold[2]);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.text(`${block.time} · ${block.duration} · ${block.type.toUpperCase()}`, margin + 4, y + 6);

      // Title
      pdf.setTextColor(cream[0], cream[1], cream[2]);
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "bold");
      pdf.text(block.title, margin + 4, y + 12);

      // Description
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(200, 195, 185);
      const lines = pdf.splitTextToSize(block.description, contentWidth - 8);
      pdf.text(lines.slice(0, 2), margin + 4, y + 17);

      y += 25;
    });

    y += 4;
  });

  // Tips
  if (itinerary.tips?.length > 0) {
    checkPageBreak(20);
    pdf.setDrawColor(gold[0], gold[1], gold[2]);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;

    pdf.setTextColor(gold[0], gold[1], gold[2]);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("✨ Travel Tips", margin, y);
    y += 8;

    itinerary.tips.forEach((tip: string) => {
      checkPageBreak(10);
      const clean = tip.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").trim();
      pdf.setTextColor(cream[0], cream[1], cream[2]);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      const lines = pdf.splitTextToSize(`→  ${clean}`, contentWidth);
      pdf.text(lines, margin, y);
      y += lines.length * 5 + 3;
    });
  }

  // Footer
  pdf.setPage(pdf.getNumberOfPages());
  pdf.setTextColor(gold[0], gold[1], gold[2]);
  pdf.setFontSize(7);
  pdf.text("Generated by ExploreYourRoute.com", pageWidth / 2, 290, { align: "center" });

  return Buffer.from(pdf.output("arraybuffer"));
}


export async function POST(req: NextRequest) {
  const rawBody = await req.text();
  const signature = req.headers.get("x-signature") ?? "";
  const rawSecret = process.env.LEMONSQUEEZY_WEBHOOK_SECRET;
  const secret = rawSecret ? rawSecret.replace(/^(["'])|(["'])$/g, "") : "";

  if (!secret) {
    console.error("LemonSqueezy webhook secret is not configured.");
    return NextResponse.json({ error: "Webhook secret not configured" }, { status: 500 });
  }

  if (!verifySignature(rawBody, signature, secret)) {
    return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
  }

  const payload = JSON.parse(rawBody);
  const eventName = payload?.meta?.event_name || payload?.event_name;
  const orderStatus =
    payload?.data?.attributes?.status ||
    payload?.data?.attributes?.order_status ||
    payload?.data?.status;

  if (orderStatus !== "paid") {
    console.log("Webhook ignored: order is not paid", { eventName, orderStatus });
    return NextResponse.json({ received: true });
  }

  const customerEmail =
    payload?.data?.attributes?.user_email ||
    payload?.data?.attributes?.customer_email ||
    payload?.data?.attributes?.billing?.email;
  const customerName =
    payload?.data?.attributes?.user_name ||
    payload?.data?.attributes?.customer_name ||
    "Traveler";

  const itineraryId =
    payload?.meta?.custom_data?.itinerary_id ||
    payload?.data?.attributes?.meta?.custom_data?.itinerary_id ||
    payload?.data?.attributes?.custom_data?.itinerary_id;

  if (!customerEmail || !itineraryId) {
    console.error("Missing email or itinerary ID", { customerEmail, itineraryId, eventName, payload });
    return NextResponse.json({ error: "Missing required webhook data" }, { status: 400 });
  }

  try {
    // ✅ NEW: fetch from KV
    const stored = await redis.get(`itinerary:${itineraryId}`);

    if (!stored) {
      console.error("Itinerary not found in Redis", itineraryId);
      return NextResponse.json({ error: "Itinerary not found" }, { status: 404 });
    }

    let itinerary: Itinerary;
    try {
      itinerary = JSON.parse(stored as string) as Itinerary;
    } catch (err) {
      console.error("Unable to parse itinerary from Redis", err);
      return NextResponse.json({ error: "Corrupted itinerary data" }, { status: 500 });
    }

    await redis.set(
      `itinerary:${itineraryId}`,
      JSON.stringify({
        ...itinerary,
        paid: true,
        orderId: payload?.data?.id || null,
        paidAt: Date.now(),
      }),
      { ex: 60 * 60 * 24 }
    );

    const pdfBuffer = generatePDFBuffer(itinerary);
    const base64PDF = pdfBuffer.toString("base64");
    const destination = itinerary.destination || "Your Trip";
    const resend = getResendClient();
    const fromAddress = process.env.RESEND_FROM_EMAIL || "support@exploreyourroute.com";

    await resend.emails.send({
      from: `ExploreYourRoute <${fromAddress}>`,
      to: customerEmail,
      subject: `Your ${destination} Itinerary PDF 🗺️`,
      html: `
        <div style="background:#1a1a2e;color:#f5f0e8;font-family:sans-serif;padding:40px;max-width:600px;margin:0 auto;border-radius:12px;">
          <h1 style="color:#c9a96e;font-size:28px;margin-bottom:8px;">Your itinerary is ready!</h1>
          <p style="opacity:0.7;margin-bottom:24px;">Hi ${customerName}, your ${destination} itinerary PDF is attached below. Have an amazing trip!</p>
          <p style="opacity:0.7;margin-bottom:24px;">If you don’t see the email in your inbox, please check your spam folder.</p>
          <div style="border-top:1px solid rgba(201,169,110,0.3);padding-top:24px;margin-top:24px;">
            <p style="opacity:0.5;font-size:12px;">Generated by <a href="https://exploreyourroute.com" style="color:#c9a96e;">ExploreYourRoute.com</a></p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: `${destination.replace(/,/g, "").replace(/\s+/g, "-")}-itinerary.pdf`,
          content: base64PDF,
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Webhook handler error:", err);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}