import { NextRequest, NextResponse } from "next/server";
import { redis } from "@/lib/kv";
import jsPDF from "jspdf";

type Block = {
  time: string;
  title: string;
  description: string;
  type: string;
  duration: string;
};

type Day = {
  date: string;
  theme: string;
  blocks: Block[];
};

type Itinerary = {
  destination: string;
  days: Day[];
  tips?: string[];
};

const orderIdRegex = /^[\w-]+$/;

function generatePDFBuffer(itinerary: Itinerary): Buffer {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const gold = [201, 169, 110];
  const dark = [26, 26, 46];
  const cream = [245, 240, 232];
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  function checkPageBreak(height: number) {
    if (y + height > 270) {
      pdf.addPage();
      y = 20;
    }
  }

  pdf.setFillColor(dark[0], dark[1], dark[2]);
  pdf.rect(0, 0, pageWidth, 297, "F");

  pdf.setTextColor(gold[0], gold[1], gold[2]);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text("EXPLOREYOURROUTE.COM", pageWidth / 2, y, { align: "center" });
  y += 8;

  pdf.setTextColor(cream[0], cream[1], cream[2]);
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text(itinerary.destination, pageWidth / 2, y + 10, { align: "center" });
  y += 20;

  pdf.setDrawColor(gold[0], gold[1], gold[2]);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  itinerary.days.forEach((day, i) => {
    checkPageBreak(20);

    pdf.setFillColor(gold[0], gold[1], gold[2]);
    pdf.roundedRect(margin, y, contentWidth, 10, 2, 2, "F");
    pdf.setTextColor(dark[0], dark[1], dark[2]);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text(`Day ${i + 1} — ${day.date}`, margin + 4, y + 7);
    pdf.setFont("helvetica", "italic");
    pdf.text(day.theme, pageWidth - margin - 4, y + 7, { align: "right" });
    y += 14;

    day.blocks.forEach((block) => {
      checkPageBreak(24);

      pdf.setFillColor(40, 35, 55);
      pdf.roundedRect(margin, y, contentWidth, 22, 2, 2, "F");

      pdf.setTextColor(gold[0], gold[1], gold[2]);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.text(`${block.time} · ${block.duration} · ${block.type.toUpperCase()}`, margin + 4, y + 6);

      pdf.setTextColor(cream[0], cream[1], cream[2]);
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "bold");
      pdf.text(block.title, margin + 4, y + 12);

      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(200, 195, 185);
      const lines = pdf.splitTextToSize(block.description, contentWidth - 8);
      pdf.text(lines.slice(0, 2), margin + 4, y + 17);

      y += 25;
    });

    y += 4;
  });

  if (Array.isArray(itinerary.tips) && itinerary.tips.length > 0) {
    checkPageBreak(20);
    pdf.setDrawColor(gold[0], gold[1], gold[2]);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;

    pdf.setTextColor(gold[0], gold[1], gold[2]);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("✨ Travel Tips", margin, y);
    y += 8;

    itinerary.tips.forEach((tip) => {
      checkPageBreak(10);
      const clean = tip.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").trim();
      pdf.setTextColor(cream[0], cream[1], cream[2]);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      const lines = pdf.splitTextToSize(`→  ${clean}`, contentWidth);
      pdf.text(lines, margin, y);
      y += lines.length * 5 + 3;
    });
  }

  pdf.setPage(pdf.getNumberOfPages());
  pdf.setTextColor(gold[0], gold[1], gold[2]);
  pdf.setFontSize(7);
  pdf.text("Generated by ExploreYourRoute.com", pageWidth / 2, 290, { align: "center" });

  return Buffer.from(pdf.output("arraybuffer"));
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const orderId =
    searchParams.get("order_id") || searchParams.get("orderId") || searchParams.get("id");

  if (!orderId || !orderIdRegex.test(orderId)) {
    return NextResponse.json({ error: "Missing or invalid order_id" }, { status: 400 });
  }

  if (!process.env.LEMONSQUEEZY_API_KEY) {
    return NextResponse.json({ error: "Missing LemonSqueezy API key" }, { status: 500 });
  }

  const orderRes = await fetch(`https://api.lemonsqueezy.com/v1/orders/${encodeURIComponent(orderId)}`, {
    headers: {
      Authorization: `Bearer ${process.env.LEMONSQUEEZY_API_KEY}`,
      Accept: "application/vnd.api+json",
    },
  });

  if (!orderRes.ok) {
    const orderError = await orderRes.text().catch(() => "");
    return NextResponse.json(
      {
        error: "Unable to fetch order details",
        details: orderError,
      },
      { status: orderRes.status }
    );
  }

  const orderData = await orderRes.json();
  const status = orderData?.data?.attributes?.status;

  if (status !== "paid") {
    return NextResponse.json({ error: "Order is not paid yet" }, { status: 400 });
  }

  let itineraryId =
    orderData?.data?.attributes?.custom_data?.itinerary_id ||
    orderData?.data?.attributes?.meta?.custom_data?.itinerary_id ||
    orderData?.data?.attributes?.meta?.custom_data?.id;

  if (!itineraryId) {
    const mappedItineraryId = await redis.get(`order:${orderId}`);
    if (mappedItineraryId && typeof mappedItineraryId === "string") {
      itineraryId = mappedItineraryId;
    }
  }

  if (!itineraryId) {
    return NextResponse.json({ error: "Missing itinerary ID in order data" }, { status: 400 });
  }

  const stored = await redis.get(`itinerary:${itineraryId}`);

  if (!stored) {
    return NextResponse.json({ error: "Itinerary not found" }, { status: 404 });
  }

  let itinerary: Itinerary;
  try {
    if (typeof stored === "string") {
      itinerary = JSON.parse(stored as string) as Itinerary;
    } else {
      itinerary = stored as Itinerary;
    }
  } catch (err) {
    console.error("Unable to parse itinerary from Redis", err, { stored });
    return NextResponse.json({ error: "Corrupted itinerary data" }, { status: 500 });
  }

  const pdfBuffer = generatePDFBuffer(itinerary);
  const pdfUrl = `data:application/pdf;base64,${pdfBuffer.toString("base64")}`;

  return NextResponse.json({ pdfUrl });
}
